
package default_package;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.6.4
 * 2024-12-11T22:43:15.887Z
 * Generated source version: 3.6.4
 *
 */
public final class FrontEndClinica_FrontEndClinicaPort_Client {

    private static final QName SERVICE_NAME = new QName("http://default_package/", "FrontEnd_ClinicaService");

    private FrontEndClinica_FrontEndClinicaPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = FrontEndClinicaService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) {
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }

        FrontEndClinicaService ss = new FrontEndClinicaService(wsdlURL, SERVICE_NAME);
        FrontEndClinica port = ss.getFrontEndClinicaPort();

        {
        System.out.println("Invoking listarEspecialidadesServer...");
        int _listarEspecialidadesServer_arg0 = -744891054;
        try {
            java.lang.String _listarEspecialidadesServer__return = port.listarEspecialidadesServer(_listarEspecialidadesServer_arg0);
            System.out.println("listarEspecialidadesServer.result=" + _listarEspecialidadesServer__return);

        } catch (NotBoundException_Exception e) {
            System.out.println("Expected exception: NotBoundException has occurred.");
            System.out.println(e.toString());
        } catch (MalformedURLException_Exception e) {
            System.out.println("Expected exception: MalformedURLException has occurred.");
            System.out.println(e.toString());
        }

            }
        {
        System.out.println("Invoking removerConsultaServer...");
        int _removerConsultaServer_arg0 = -424035282;
        int _removerConsultaServer_arg1 = -107317660;
        try {
            java.lang.String _removerConsultaServer__return = port.removerConsultaServer(_removerConsultaServer_arg0, _removerConsultaServer_arg1);
            System.out.println("removerConsultaServer.result=" + _removerConsultaServer__return);

        } catch (NotBoundException_Exception e) {
            System.out.println("Expected exception: NotBoundException has occurred.");
            System.out.println(e.toString());
        } catch (MalformedURLException_Exception e) {
            System.out.println("Expected exception: MalformedURLException has occurred.");
            System.out.println(e.toString());
        }

            }
        {
        System.out.println("Invoking listarClinicasServer...");
        try {
            java.lang.String _listarClinicasServer__return = port.listarClinicasServer();
            System.out.println("listarClinicasServer.result=" + _listarClinicasServer__return);

        } catch (NotBoundException_Exception e) {
            System.out.println("Expected exception: NotBoundException has occurred.");
            System.out.println(e.toString());
        } catch (MalformedURLException_Exception e) {
            System.out.println("Expected exception: MalformedURLException has occurred.");
            System.out.println(e.toString());
        }

            }
        {
        System.out.println("Invoking autenticar...");
        java.lang.String _autenticar_arg0 = "_autenticar_arg0669078867";
        java.lang.String _autenticar_arg1 = "_autenticar_arg1-915416468";
        try {
            java.lang.String _autenticar__return = port.autenticar(_autenticar_arg0, _autenticar_arg1);
            System.out.println("autenticar.result=" + _autenticar__return);

        } catch (IOException_Exception e) {
            System.out.println("Expected exception: IOException has occurred.");
            System.out.println(e.toString());
        }

            }
        {
        System.out.println("Invoking marcarConsultasServer...");
        int _marcarConsultasServer_arg0 = 2004851937;
        int _marcarConsultasServer_arg1 = 1207080168;
        int _marcarConsultasServer_arg2 = 199871212;
        int _marcarConsultasServer_arg3 = -51204303;
        int _marcarConsultasServer_arg4 = -1468411854;
        int _marcarConsultasServer_arg5 = 182904682;
        int _marcarConsultasServer_arg6 = -1339325470;
        try {
            java.lang.String _marcarConsultasServer__return = port.marcarConsultasServer(_marcarConsultasServer_arg0, _marcarConsultasServer_arg1, _marcarConsultasServer_arg2, _marcarConsultasServer_arg3, _marcarConsultasServer_arg4, _marcarConsultasServer_arg5, _marcarConsultasServer_arg6);
            System.out.println("marcarConsultasServer.result=" + _marcarConsultasServer__return);

        } catch (NotBoundException_Exception e) {
            System.out.println("Expected exception: NotBoundException has occurred.");
            System.out.println(e.toString());
        } catch (MalformedURLException_Exception e) {
            System.out.println("Expected exception: MalformedURLException has occurred.");
            System.out.println(e.toString());
        }

            }
        {
        System.out.println("Invoking registar...");
        java.lang.String _registar_arg0 = "_registar_arg0-733244148";
        java.lang.String _registar_arg1 = "_registar_arg1420098440";
        try {
            java.lang.String _registar__return = port.registar(_registar_arg0, _registar_arg1);
            System.out.println("registar.result=" + _registar__return);

        } catch (IOException_Exception e) {
            System.out.println("Expected exception: IOException has occurred.");
            System.out.println(e.toString());
        }

            }
        {
        System.out.println("Invoking listarConsultasServer...");
        int _listarConsultasServer_arg0 = 1211611949;
        try {
            java.lang.String _listarConsultasServer__return = port.listarConsultasServer(_listarConsultasServer_arg0);
            System.out.println("listarConsultasServer.result=" + _listarConsultasServer__return);

        } catch (NotBoundException_Exception e) {
            System.out.println("Expected exception: NotBoundException has occurred.");
            System.out.println(e.toString());
        } catch (MalformedURLException_Exception e) {
            System.out.println("Expected exception: MalformedURLException has occurred.");
            System.out.println(e.toString());
        }

            }

        System.exit(0);
    }

}
