
package default_package;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.6.4
<<<<<<< HEAD
 * 2024-12-06T17:21:28.408Z
=======
 * 2024-12-05T11:42:16.994Z
>>>>>>> 3c35b6d43e9ac97ecd20498e32cbef41fe187890
 * Generated source version: 3.6.4
 */

@WebFault(name = "IOException", targetNamespace = "http://default_package/")
public class IOException_Exception extends Exception {

    private default_package.IOException faultInfo;

    public IOException_Exception() {
        super();
    }

    public IOException_Exception(String message) {
        super(message);
    }

    public IOException_Exception(String message, java.lang.Throwable cause) {
        super(message, cause);
    }

    public IOException_Exception(String message, default_package.IOException ioException) {
        super(message);
        this.faultInfo = ioException;
    }

    public IOException_Exception(String message, default_package.IOException ioException, java.lang.Throwable cause) {
        super(message, cause);
        this.faultInfo = ioException;
    }

    public default_package.IOException getFaultInfo() {
        return this.faultInfo;
    }
}
