import org.apache.cxf.jaxws.JaxWsProxyFactoryBean;
import java.util.Scanner;
import default_package.FrontEndClinica;
import default_package.MalformedURLException_Exception;
import default_package.NotBoundException_Exception;


public class Consumer {

    public static void main(String[] args) throws NotBoundException_Exception, MalformedURLException_Exception {

        JaxWsProxyFactoryBean factory = new JaxWsProxyFactoryBean();        

        // Use the URL defined in the soap address portion of the WSDL
        factory.setAddress("http://localhost:8080/CD_FrontEnd_Soap/services/FrontEnd_ClinicaPort"); 
       
        // Utilize the class which was auto-generated by Apache CXF wsdl2java
        factory.setServiceClass(FrontEndClinica.class);        

        Object client = factory.create();
        Scanner scanner = new Scanner(System.in);
        

        while (true) {
            System.out.println("\n--- SOAP Client Menu ---");
            System.out.println("1. Listar Consultas");
            System.out.println("2. Outra Operação");
            System.out.println("3. Sair");
            System.out.print("Escolha uma opção: ");
            
            int choice = scanner.nextInt();
            scanner.nextLine();

            switch (choice) {
                case 1:
                	
                    System.out.print("Digite o ID para listar consultas: ");
                    int id = scanner.nextInt();
                    scanner.nextLine();
                    try {	
                    	String response = ((FrontEndClinica)client).listarConsultasServer(id);
                    	System.out.println(response); 
                    	
                    } catch (SecurityException | IllegalArgumentException e) {
                        e.printStackTrace();
                    }
                    break;
                    
                case 2:
                    System.out.println("Opção não implementada.");
                    break;
                case 3:
                    System.out.println("Encerrando o cliente.");
                    scanner.close();
                    return;
                default:
                    System.out.println("Opção inválida. Tente novamente.");
            }
        }
        
        
        
    }
}









